# Generated by Django 4.0.3 on 2022-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=125)),
                ('shop', models.CharField(max_length=125)),
                ('salary', models.IntegerField(default=0)),
                ('telegram_id', models.CharField(max_length=125)),
                ('bons', models.IntegerField(default=0)),
            ],
        ),
    ]
